version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    environment:
      DJANGO_SETTINGS_MODULE: "swimmingplaces.settings"
    ports:
      - "8000:8000"
      - "5678:5678" #Debug
    depends_on:
      - db
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: testpassword
    